environment:
  nuget_key: nRTnNdFfpgWh2dk3i3d62uOl4ShGuKpH0VMaLAQ0P3S5G52hX/HNExz/y6gf142t
    secure: 

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Build worker image (VM template)
image: Visual Studio 2017

# build cache to preserve files/folders between builds
cache:
  - packages

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - ps: build\add-externals.ps1
  - nuget restore "source\Elasticsearch Inside.sln"
  
build:
  parallel: true                            # enable MSBuild parallel builds
  project: source\Elasticsearch Inside.sln  # path to Visual Studio solution or project
  publish_nuget: false                      # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false              # generate and publish NuGet symbol packages

test:
  assemblies:
    - '**\*.tests.dll'
